### ISSUE TITLE
Exception at the start of tomcat server in rest module

### ISSUE THREAD

**Issue by arrynn** [MichalBeran/Movies-Catalogue#94]
SEVERE: Unable to process Jar entry [module-info.class] from Jar [jar:file:/Users/marek/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar!/] for annotations
org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
        at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:133)
        at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:60)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:209)
        at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:119)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2134)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2010)
        at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1976)
        at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1961)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1319)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:878)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:376)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:119)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5322)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by MichalBeran** [comment]
Added new dependency to solve this problem

**Comment by wgoldman1** [comment]
> Added new dependency to solve this problem

what was the new dependency that was added to solve the problem?

**Comment by MichalBeran** [comment]
See Pull Request  #98

**Comment by MichalBeran** [comment]
look at pull request #98
